name: Build/Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Build & Publish Release
        run: pnpm run electron:build -- --publish always
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
